# Generated by Django 5.2.17 on 2026-10-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Menu')),
                ('category', models.CharField(choices=[('makanan_berat', 'Makanan Berat (Nasi/Mie/Olahan)'), ('snack', 'Snack / Kue Basah / Roti'), ('minuman', 'Minuman'), ('lainnya', 'Lainnya')], default='snack', max_length=30, verbose_name='Kategori Menu')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='Foto Menu')),
                ('price_customer', models.PositiveIntegerField(default=10000, verbose_name='Harga Pelanggan (Rp)')),
                ('price_partner', models.PositiveIntegerField(default=9000, verbose_name='Bagi Hasil Mitra (Rp)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Menu Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='branches.branch', verbose_name='Cabang Gerai')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='partners.partner', verbose_name='Mitra UMKM')),
            ],
            options={
                'verbose_name': 'Menu Produk',
                'verbose_name_plural': 'Menu Produk',
                'db_table': 'products',
                'ordering': ['branch', 'category', 'name'],
                'indexes': [models.Index(fields=['branch', 'is_active'], name='products_branch__81f2ce_idx'), models.Index(fields=['partner', 'is_active'], name='products_partner_f4f91e_idx')],
            },
        ),
    ]
