# Generated by Django 5.2.17 on 2026-10-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nama Mitra')),
                ('phone_number', models.CharField(blank=True, max_length=25, verbose_name='Nomor WhatsApp')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='Nama Bank / E-Wallet')),
                ('bank_account_name', models.CharField(blank=True, max_length=150, verbose_name='Nama Pemilik Rekening')),
                ('bank_account_number', models.CharField(blank=True, max_length=60, verbose_name='Nomor Rekening')),
                ('default_payment_method', models.CharField(choices=[('transfer', 'Transfer Bank / E-Wallet'), ('cash', 'Tunai / Cash')], default='transfer', max_length=20, verbose_name='Metode Pembayaran Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Mitra Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mitra UMKM',
                'verbose_name_plural': 'Mitra UMKM',
                'db_table': 'partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Tanggal Rencana Drop (Besok)')),
                ('status', models.CharField(choices=[('hadir', 'Hadir Besok'), ('libur', 'Libur / Tidak Antar')], default='hadir', max_length=20, verbose_name='Status Kehadiran')),
                ('estimated_arrival_time', models.TimeField(blank=True, null=True, verbose_name='Perkiraan Waktu Tiba (Subuh - 08:00)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Catatan Drop Barang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='branches.branch', verbose_name='Cabang')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='partners.partner', verbose_name='Mitra UMKM')),
            ],
            options={
                'verbose_name': 'Absensi H-1 Mitra',
                'verbose_name_plural': 'Absensi H-1 Mitra',
                'db_table': 'daily_attendances',
                'ordering': ['-date', 'branch', 'partner'],
                'constraints': [models.UniqueConstraint(fields=('date', 'partner', 'branch'), name='unique_partner_attendance_per_date_branch')],
            },
        ),
    ]
