# Generated by Django 5.2.17 on 2026-10-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='default_payment_method',
        ),
    ]
