# Generated by Django 5.2.17 on 2026-10-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('partners', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Tanggal Transaksi')),
                ('stock_in', models.PositiveIntegerField(default=0, verbose_name='Barang Masuk Pagi (Pcs)')),
                ('stock_left', models.PositiveIntegerField(default=0, verbose_name='Sisa Sore / Tutup Toko (Pcs)')),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='proof_photos/%Y/%m/%d/', verbose_name='Foto Bukti Serah Terima Fisik (Retensi H+7)')),
                ('proof_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Upload Bukti')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending / Belum Ditransfer'), ('transferred', 'Ditransfer (Bank / E-Wallet)'), ('paid_cash', 'Dibayar Tunai (Cash)')], default='pending', max_length=20, verbose_name='Status Pembayaran Bagi Hasil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stocks', to='branches.branch', verbose_name='Cabang')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stocks', to='partners.partner', verbose_name='Mitra UMKM')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stocks', to='products.product', verbose_name='Menu Makanan')),
            ],
            options={
                'verbose_name': 'Stok & Transaksi Harian',
                'verbose_name_plural': 'Stok & Transaksi Harian',
                'db_table': 'daily_stocks',
                'ordering': ['-date', 'branch', 'partner', 'product'],
                'indexes': [models.Index(fields=['date', 'branch'], name='idx_dstk_date_branch'), models.Index(fields=['partner', 'date'], name='idx_dstk_partner_date')],
                'constraints': [models.UniqueConstraint(fields=('date', 'branch', 'product'), name='unique_stock_per_date_branch_product')],
            },
        ),
    ]
