# Generated by Django 5.2.17 on 2026-10-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Tanggal Rekap')),
                ('cash_setor', models.BigIntegerField(default=0, verbose_name='Uang Setor Tunai Kasir (Rp)')),
                ('cash_uang_besar', models.BigIntegerField(default=0, verbose_name='Uang Kertas Besar (Rp50k/Rp100k)')),
                ('cash_uang_receh', models.BigIntegerField(default=0, verbose_name='Uang Kertas Kecil & Logam (Rp)')),
                ('gopay_merchant', models.BigIntegerField(default=0, verbose_name='Penerimaan QRIS / GoPay Merchant (Rp)')),
                ('cash_terpakai_gaji', models.BigIntegerField(default=0, verbose_name='Pengeluaran Gaji Harian Kasir/Kru (Rp)')),
                ('cash_terpakai_makan', models.BigIntegerField(default=0, verbose_name='Pengeluaran Uang Makan Kru (Rp)')),
                ('cash_terpakai_operasional', models.BigIntegerField(default=0, verbose_name='Pengeluaran Operasional Toko  (Plastik, Kantung Plastik, dll)')),
                ('selisih', models.BigIntegerField(default=0, verbose_name='Selisih Kas / Rekonsiliasi (Rp)')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan Kasir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to='branches.branch', verbose_name='Cabang')),
            ],
            options={
                'verbose_name': 'Resume Kas Kasir',
                'verbose_name_plural': 'Resume Kas Kasir',
                'db_table': 'daily_cashflows',
                'ordering': ['-date', 'branch'],
                'constraints': [models.UniqueConstraint(fields=('date', 'branch'), name='unique_cashflow_per_date_branch')],
            },
        ),
    ]
