# Generated by Django 5.2.17 on 2026-10-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama Cabang')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug Cabang')),
                ('address', models.TextField(verbose_name='Alamat Lengkap')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('gmaps_url', models.URLField(max_length=300, verbose_name='Google Maps URL')),
                ('opening_hours', models.CharField(default='06:00 - 10:00 WIB', max_length=60, verbose_name='Jam Operasional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cabang Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cabang',
                'verbose_name_plural': 'Cabang',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
    ]
